#proxy:
#  volumes:
#    - nginx_config:/etc/nginx
#    - nginx_releasenote:/usr/share/nginx/html

sonar:
  volumes:
    - sonar_data:/opt/sonarqube/data
    - sonar_extensions:/opt/sonarqube/extensions 
    - sonar_logs:/opt/sonarqube/logs

jenkins-slave:
  volumes:
    - jenkins_slave_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins:
  user: root 
  volumes:
    - jenkins_home:/var/jenkins_home 
    - /var/run/docker.sock:/var/run/docker.sock

nexus:
  volumes:
    - nexus_sonatype_work:/sonatype-work

registry:
  volumes:
    - registry_certs:/certs
    - registry_data:/data
